LPD-7203 Link notification to the Conflicts Checking page
liferay-publications/liferay-portal pull request #1007
Opened 2024-02-01 15:52 UTC by gislayne-vitorino

2024-02-01 15:52 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2024-02-01 15:54 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-30.liferay.com/job/test-portal-source-format/5369/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/5369/jenkins-report.html">here</a>.</b></p>

2024-02-01 15:56 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7c720a2bc9c2a31d7f3ecd5144844851331557c4">7c720a2bc9c2a31d7f3ecd5144844851331557c4</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/gislayne-vitorino/liferay-portal/tree/LPD-7203">LPD-7203</a><br/>Branch GIT ID: <a href="https://github.com/gislayne-vitorino/liferay-portal/commit/e2b226bbd1c0ba123960f7a690a0af62259b86a5">e2b226bbd1c0ba123960f7a690a0af62259b86a5</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-30.liferay.com/job/test-portal-source-format/5369/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/5369/jenkins-report.html">here</a>.</h5></details></html>

2024-02-01 15:58 UTC, gislayne-vitorino commented
ci:test:sf

2024-02-01 15:58 UTC, gislayne-vitorino commented
ci:test:publications

2024-02-01 15:59 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-30.liferay.com/job/test-portal-source-format/5369/">test-portal-source-format#5369</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/5369/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-publications/liferay-portal/pull/1007">liferay-publications#1007</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2533463555">[master] ci:test:sf - gislayne-vitorino &gt; liferay-publications - PR#1007 - 2024-02-01[07:53:03]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2533463555<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-30.liferay.com/job/publish-testray-report/20813/">publish-testray-report#20813</a><br/></div></div>

2024-02-01 15:59 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>publications</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest(master)/5271/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-35.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5271/jenkins-report.html">here</a>.</b></p>

2024-02-01 16:00 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-26.liferay.com/job/test-portal-source-format/7501/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/7501/jenkins-report.html">here</a>.</b></p>

2024-02-01 16:02 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7c720a2bc9c2a31d7f3ecd5144844851331557c4">7c720a2bc9c2a31d7f3ecd5144844851331557c4</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/gislayne-vitorino/liferay-portal/tree/LPD-7203">LPD-7203</a><br/>Branch GIT ID: <a href="https://github.com/gislayne-vitorino/liferay-portal/commit/ce06af61167afa3be98e1b1f8c16546d2cb1b094">ce06af61167afa3be98e1b1f8c16546d2cb1b094</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-26.liferay.com/job/test-portal-source-format/7501/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/7501/jenkins-report.html">here</a>.</h5></details></html>

2024-02-01 16:06 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-26.liferay.com/job/test-portal-source-format/7501/">test-portal-source-format#7501</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/7501/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-publications/liferay-portal/pull/1007">liferay-publications#1007</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2533465004">[master] ci:test:sf - gislayne-vitorino &gt; liferay-publications - PR#1007 - 2024-02-01[07:58:38]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2533465004<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-26.liferay.com/job/publish-testray-report/29439/">publish-testray-report#29439</a><br/></div></div>

2024-02-01 16:08 UTC, gislayne-vitorino commented
ci:test:stop

2024-02-01 16:08 UTC, liferay-continuous-integration commented
The test suite specified is not a valid test suite.
Please refer to the available test suites below.
#### ci:test[:suite][:SHA|nocompile|norebase|gist-SHA]
&nbsp;&nbsp;&nbsp;&nbsp;Test the pull request. Optionally specify the name of the test suite and/or optionally specify the upstream SHA to test against or use "nocompile" to test with a prebuilt bundle or use "norebase" to test without rebasing.
<details><summary><strong>Available test suites:</strong></summary>

- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**acceptance** - Test acceptance tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**acceptance-functional** - Test acceptance functional tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**acceptance-functional-db-partition** - Test acceptance functional tests with Database Partitioning.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**acceptance-release** - Compile a release bundle and execute acceptance tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**acceptance-upstream** - Test acceptance upstream tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**accessibility** - Test all accessibility tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**accessibility-menu** - Test all accessibility menu tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**account** - Test Account tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**analytics-cloud** - Test Analytics Cloud tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**analytics-cloud-acceptance** - No description is available.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**analytics-cloud-integration** - No description is available.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**analytics-cloud-quarantine** - No description is available.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**app-servers** - Test Deployments on App Servers.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**auto-tagging** - Test Auto Tagging tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**backend** - Test backend tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**backend-hypersonic** - Test backend tests on Hypersonic.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**blade** - Test Blade samples tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**blogs** - Test Blogs tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**bulk-editing** - Test Bulk Editing tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**bundle** - Saves a compiled tomcat bundle.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**calendar** - Test Calendar tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**clay** - Test Clay component tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**click-to-chat** - Test Click to Chat tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**clustering** - Test clustering tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**comment** - Test Comment tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**commerce** - Test only Commerce tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**commerce-database** - Test only Commerce Database tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**commerce-es7-remote** - Test only Commerce tests with the latest compatible remote Elasticsearch 7 version.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**commerce-es8-remote** - Test only Commerce tests with the latest compatible remote Elasticsearch 8 version.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**commerce-functional** - Test only Commerce functional tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**commerce-integration** - Test only Commerce integration tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**commerce-upgrade** - No description is available.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**configuration-framework** - Test Configuration Framework component tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**content-page-review** - Test Content Page Review (comments) tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**continuous-integration** - Test Continuous Integration tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**cookies** - Test Cookie Preferences tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**data-engine** - Test Data Engine functional tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**data-engine-db-partition** - Test Data Engine functional tests with Database Partitioning.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**data-integration** - Test only Data Integration tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**data-integration-functional** - Test only functional Data Integration tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**db-partition** - Test Database Partitioning functional tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**depot** - Test Depot tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**digital-signature** - Test Digital Signature tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**dl-store** - Test Document Library Store tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**document** - Test Document and Media tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**document-antivirus** - Test Antivirus against DM.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**drools** - Test Drools tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**dummy** - No description is available.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**echo** - Test all Echo (WCM) team tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**echo-acceptance** - Test Echo (WCM) team acceptance tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**echo-accessibility** - Test Echo (WCM) team accessibility tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**echo-analytics-cloud** - Test segmentation and personalization with Analytics Cloud.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**echo-db-partition** - Test Echo (WCM) team acceptance tests with Database Partitioning.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**echo-headless** - Test Echo (WCM) team headless components.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**echo-upgrade** - Test Echo (WCM) team upgrade tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**environments** - Test environment acceptance functional tests on all available environment stacks.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**export-import** - Test exportimport tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**forms** - Test forms tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**forms-db-partition** - Test forms functional tests with Database Partitioning.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**forms-functional** - Test only functional forms tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**friendly-url** - Test Friendly URL tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**frontend** - Test all Frontend Infra team tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**frontend-client-extensions** - Test frontend client extensions tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**frontend-data-set** - Test frontend data set tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**frontend-dev-exp** - Test frontend developer experience tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**frontend-ui** - Test frontend ui tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**frontend-walkthrough** - Test frontend walkthrough tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**gauntlet** - Test upstream tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**gauntlet-bucket** - Test a subset of upstream tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**gradle-plugins** - Test Gradle Plugins tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**headless** - Test all headless team tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**headless-acceptance** - Test headless team acceptance tests considering Headless and Rest Builder.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**headless-builder** - All tests for Headless Builder component.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**headless-builder-functional** - All functional tests for Headless Builder component.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**headless-functional** - Headless Team functional API tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**hotel** - Test all Source Formatter unit tests related to upgrade
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**item-selector** - Test item selector tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**jacoco-report** - Test integration and unit tests to generate JaCoCo reports.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**jdk11** - Test acceptance, smoke, and upgrade functional tests against JDK11.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**jsf** - Test Liferay Faces tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**kaleo-forms** - Test Kaleo Forms admin tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**knowledge-base** - No description is available.
 [...]

2024-02-01 16:09 UTC, gislayne-vitorino commented
ci:stop

2024-02-01 16:10 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:publications - 0 out of 1 jobs passed in 11 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7c720a2bc9c2a31d7f3ecd5144844851331557c4">7c720a2bc9c2a31d7f3ecd5144844851331557c4</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/af15c5eb3044f095c04cff18cc08e9e532ace36c">af15c5eb3044f095c04cff18cc08e9e532ace36c</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2533134009">EE Development Acceptance (master) - 339 - 2024-01-30[19:20:24]</a></p><details><summary><strong>ci:test:publications - 0 out of 1 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest(master)/5271/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li></ul></div></details><h5>For more details click <a href="https://test-1-35.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5271/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest(master)/5271/">test-portal-acceptance-pullrequest(master)</a></h5><div><h6>Job Results:</h6><p>0 Jobs Passed.<br/>1 Job Failed.</p></div><pre>Build was aborted</pre></div></li></ol><h4>For upstream results, click <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html><h5>Test bundle downloads:</h5><ul><li><a href="https://files.liferay.com/private/bundles/test-1-35/jobs/test-portal-acceptance-pullrequest(master)/builds/5271/liferay-portal-bundle-tomcat.tar.gz">liferay-portal-bundle-tomcat.tar.gz</a> (mirrors: <a href="http://mirrors.dlc.liferay.com/files.liferay.com/private/bundles/test-1-35/jobs/test-portal-acceptance-pullrequest(master)/builds/5271/liferay-portal-bundle-tomcat.tar.gz">dlc</a>, <a href="http://mirrors.lax.liferay.com/files.liferay.com/private/bundles/test-1-35/jobs/test-portal-acceptance-pullrequest(master)/builds/5271/liferay-portal-bundle-tomcat.tar.gz">lax</a>)</li></ul>

2024-02-01 16:11 UTC, gislayne-vitorino commented
ci:test:sf

2024-02-01 16:11 UTC, gislayne-vitorino commented
ci:test:publications

2024-02-01 16:13 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest(master)/5271/">test-portal-acceptance-pullrequest(master)#5271</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-35.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5271/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>publications<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-publications/liferay-portal/pull/1007">liferay-publications#1007</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2533465096">[master] ci:test:publications - gislayne-vitorino &gt; liferay-publications - PR#1007 - 2024-02-01[07:58:40]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2533465096<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-35.liferay.com/job/publish-testray-report/11583/">publish-testray-report#11583</a><br/></div></div>

2024-02-01 16:13 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-12.liferay.com/job/test-portal-source-format/5798/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-12.liferay.com/userContent/jobs/test-portal-source-format/builds/5798/jenkins-report.html">here</a>.</b></p>

2024-02-01 16:16 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7c720a2bc9c2a31d7f3ecd5144844851331557c4">7c720a2bc9c2a31d7f3ecd5144844851331557c4</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/gislayne-vitorino/liferay-portal/tree/LPD-7203">LPD-7203</a><br/>Branch GIT ID: <a href="https://github.com/gislayne-vitorino/liferay-portal/commit/c57dbeb9032c692f1209ba3b81ec67575941e352">c57dbeb9032c692f1209ba3b81ec67575941e352</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-12.liferay.com/job/test-portal-source-format/5798/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-12.liferay.com/userContent/jobs/test-portal-source-format/builds/5798/jenkins-report.html">here</a>.</h5></details></html>

2024-02-01 16:22 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-12.liferay.com/job/test-portal-source-format/5798/">test-portal-source-format#5798</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-12.liferay.com/userContent/jobs/test-portal-source-format/builds/5798/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-publications/liferay-portal/pull/1007">liferay-publications#1007</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2533467834">[master] ci:test:sf - gislayne-vitorino &gt; liferay-publications - PR#1007 - 2024-02-01[08:12:03]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2533467834<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-12.liferay.com/job/publish-testray-report/4570/">publish-testray-report#4570</a><br/></div></div>

2024-02-01 16:22 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>publications</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/10232/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/10232/jenkins-report.html">here</a>.</b></p>

2024-02-01 18:40 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:publications - 90 out of 100 jobs passed in 2 hours 18 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7c720a2bc9c2a31d7f3ecd5144844851331557c4">7c720a2bc9c2a31d7f3ecd5144844851331557c4</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7c720a2bc9c2a31d7f3ecd5144844851331557c4">7c720a2bc9c2a31d7f3ecd5144844851331557c4</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2533504821">EE Development Acceptance (master) - 342 - 2024-02-01[04:41:08]</a></p><details><summary><strong>ci:test:publications - 90 out of 100 jobs PASSED</strong></summary><div><h4>10 Failed Jobs:</h4><ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/10232/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/919202/">central-requirements-jdk8/0/0</a></li></ul></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/891116/">functional-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/919193/">functional-tomcat90-mysql57-jdk8/1/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/515652/">functional-tomcat90-mysql57-jdk8/1/1</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/841446/">functional-tomcat90-mysql57-jdk8/1/2</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/919194/">functional-tomcat90-mysql57-jdk8/1/3</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/800985/">functional-tomcat90-mysql57-jdk8/1/4</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/800984/">functional-tomcat90-mysql57-jdk8/1/5</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/788951/">functional-tomcat90-mysql57-jdk8/1/6</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/515653/"><strike>functional-tomcat90-mysql57-jdk8/1/7</strike></a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/360897/">functional-tomcat90-mysql57-jdk8/1/8</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/354649/">functional-tomcat90-mysql57-jdk8/1/9</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/828053/">functional-tomcat90-mysql57-jdk8/1/10</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/354652/">functional-tomcat90-mysql57-jdk8/1/11</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/389190/">functional-tomcat90-mysql57-jdk8/1/12</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/355981/">functional-tomcat90-mysql57-jdk8/1/13</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/825111/">functional-tomcat90-mysql57-jdk8/1/14</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/919199/">functional-tomcat90-mysql57-jdk8/1/15</a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/350919/">functional-tomcat90-mysql57-jdk8/1/16</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/841449/">functional-tomcat90-mysql57-jdk8/1/17</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/389189/"><strike>functional-tomcat90-mysql57-jdk8/1/18</strike></a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/354651/"><strike>functional-tomcat90-mysql57-jdk8/1/19</strike></a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/360899/">functional-tomcat90-mysql57-jdk8/1/20</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/788953/">functional-tomcat90-mysql57-jdk8/1/21</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/859849/">functional-tomcat90-mysql57-jdk8/1/22</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/747508/">functional-tomcat90-mysql57-jdk8/1/23</a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/318786/">functional-tomcat90-mysql57-jdk8/1/24</a></li><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/332990/">functional-tomcat90-mysql57-jdk8/2/0</a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/360900/">functional-tomcat90-mysql57-jdk8/2/1</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/287627/">functional-tomcat90-mysql57-jdk8/2/2</a></li><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/363352/">functional-tomcat90-mysql57-jdk8/2/3</a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/350920/">functional-tomcat90-mysql57-jdk8/2/4</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/800992/">functional-tomcat90-mysql57-jdk8/2/5</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/346949/">functional-tomcat90-mysql57-jdk8/2/6</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/840549/">functional-tomcat90-mysql57-jdk8/2/7</a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/318788/">functional-tomcat90-mysql57-jdk8/2/8</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/919191/">functional-tomcat90-mysql57-jdk8/2/9</a></li><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/332989/">functional-tomcat90-mysql57-jdk8/2/10</a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/350918/">functional-tomcat90-mysql57-jdk8/2/11</a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/360898/">functional-tomcat90-mysql57-jdk8/2/12</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/800988/">functional-tomcat90-mysql57-jdk8/2/13</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/828051/">functional-tomcat90-mysql57-jdk8/2/14</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/825109/">functional-tomcat90-mysql57-jdk8/2/15</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/800989/" [...]

2024-02-01 18:44 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/10232/">test-portal-acceptance-pullrequest(master)#10232</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/10232/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>publications<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-publications/liferay-portal/pull/1007">liferay-publications#1007</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2533574953">[master] ci:test:publications - gislayne-vitorino &gt; liferay-publications - PR#1007 - 2024-02-01[08:21:51]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2533574953<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-38.liferay.com/job/publish-testray-report/20999/">publish-testray-report#20999</a><br/></div></div>

2024-02-01 19:18 UTC, pei-jung requested changes

2024-02-01 19:18 UTC, pei-jung commented on modules/apps/change-tracking/change-tracking-test/src/testIntegration/java/com/liferay/change/tracking/internal/test/PublicationUserNotificationHandlerTest.java
> +
If you're popping the service context in a tearDown, you should do the push in the setUp and assign the service context object to a class var. 

Another option is to do it locally in each tests with a try-finally bock.

2024-02-02 18:24 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>publications</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/8558/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8558/jenkins-report.html">here</a>.</b></p>

2024-02-02 18:26 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/540b29f1304903707051eb67691081d4e0cf215e">540b29f1304903707051eb67691081d4e0cf215e</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/gislayne-vitorino/liferay-portal/tree/LPD-7203">LPD-7203</a><br/>Branch GIT ID: <a href="https://github.com/gislayne-vitorino/liferay-portal/commit/56a551b37c141381a28d73029ae7e27877e0cdcf">56a551b37c141381a28d73029ae7e27877e0cdcf</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-28.liferay.com/job/test-portal-source-format/5082/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/5082/jenkins-report.html">here</a>.</h5></details></html>

2024-02-02 18:29 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-28.liferay.com/job/test-portal-source-format/5082/">test-portal-source-format#5082</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/5082/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-publications/liferay-portal/pull/1007">liferay-publications#1007</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2534141434">[master] ci:test:sf - gislayne-vitorino &gt; liferay-publications - PR#1007 - 2024-02-02[10:23:51]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2534141434<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-28.liferay.com/job/publish-testray-report/19837/">publish-testray-report#19837</a><br/></div></div>

2024-02-02 20:39 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:publications - 87 out of 100 jobs passed in 2 hours 15 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/540b29f1304903707051eb67691081d4e0cf215e">540b29f1304903707051eb67691081d4e0cf215e</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d301aea2246a87ce6cb26441782e8e5b4f71ee8f">d301aea2246a87ce6cb26441782e8e5b4f71ee8f</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2534252432">EE Development Acceptance (master) - 343 - 2024-02-02[00:43:04]</a></p><details><summary><strong>ci:test:publications - 87 out of 100 jobs PASSED</strong></summary><div><h4>13 Failed Jobs:</h4><ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/8558/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/843162/">central-requirements-jdk8/0/0</a></li></ul></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/862174/">functional-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/934199/">functional-tomcat90-mysql57-jdk8/1/0</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/803072/">functional-tomcat90-mysql57-jdk8/1/1</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/934200/">functional-tomcat90-mysql57-jdk8/1/2</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/803073/">functional-tomcat90-mysql57-jdk8/1/3</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/830111/">functional-tomcat90-mysql57-jdk8/1/4</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/516406/">functional-tomcat90-mysql57-jdk8/1/5</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1019804/">functional-tomcat90-mysql57-jdk8/1/6</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/791442/"><strike>functional-tomcat90-mysql57-jdk8/1/7</strike></a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/516407/">functional-tomcat90-mysql57-jdk8/1/8</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/921315/">functional-tomcat90-mysql57-jdk8/1/9</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/843159/">functional-tomcat90-mysql57-jdk8/1/10</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/921320/">functional-tomcat90-mysql57-jdk8/1/11</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/827183/">functional-tomcat90-mysql57-jdk8/1/12</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/862177/">functional-tomcat90-mysql57-jdk8/1/13</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/516412/">functional-tomcat90-mysql57-jdk8/1/14</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/547817/">functional-tomcat90-mysql57-jdk8/1/15</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1019809/">functional-tomcat90-mysql57-jdk8/1/16</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/934203/">functional-tomcat90-mysql57-jdk8/1/17</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/893034/"><strike>functional-tomcat90-mysql57-jdk8/1/18</strike></a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/843157/"><strike>functional-tomcat90-mysql57-jdk8/1/19</strike></a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/921318/">functional-tomcat90-mysql57-jdk8/1/20</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/862175/">functional-tomcat90-mysql57-jdk8/1/21</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/516410/">functional-tomcat90-mysql57-jdk8/1/22</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1019807/">functional-tomcat90-mysql57-jdk8/1/23</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/934204/">functional-tomcat90-mysql57-jdk8/1/24</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/791402/">functional-tomcat90-mysql57-jdk8/2/0</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/934207/">functional-tomcat90-mysql57-jdk8/2/1</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/803079/">functional-tomcat90-mysql57-jdk8/2/2</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1019803/">functional-tomcat90-mysql57-jdk8/2/3</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/830117/">functional-tomcat90-mysql57-jdk8/2/4</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/921322/">functional-tomcat90-mysql57-jdk8/2/5</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/893039/">functional-tomcat90-mysql57-jdk8/2/6</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1021123/">functional-tomcat90-mysql57-jdk8/2/7</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/749496/">functional-tomcat90-mysql57-jdk8/2/8</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/547813/">functional-tomcat90-mysql57-jdk8/2/9</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/547816/">functional-tomcat90-mysql57-jdk8/2/10</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/893032/">functional-tomcat90-mysql57-jdk8/2/11</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/921317/">functional-tomcat90-mysql57-jdk8/2/12</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/827181/">functional-tomcat90-mysql57-jdk8/2/13</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/830114/">functional-tomcat90-mysql57-jdk8/2/14</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/791400/">functional-tomcat90-mysql57-jdk8/2/15</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(mast [...]

2024-02-02 20:42 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/8558/">test-portal-acceptance-pullrequest(master)#8558</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8558/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>publications<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-publications/liferay-portal/pull/1007">liferay-publications#1007</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2534268119">[master] ci:test:publications - gislayne-vitorino &gt; liferay-publications - PR#1007 - 2024-02-02[10:24:02]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2534268119<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/17366/">publish-testray-report#17366</a><br/></div></div>

2024-02-04 06:12 UTC, pei-jung commented
Good work, @gislayne-vitorino! See my changes in https://github.com/liferay-publications/liferay-portal/pull/1013.

2024-02-04 06:12 UTC, closed without merging