LPD-18648 Delete notification if it is no longer relevant
liferay-publications/liferay-portal pull request #1056
Opened 2024-02-23 18:54 UTC by brookedalton

https://liferay.atlassian.net/browse/LPD-18648

2024-02-23 18:57 UTC, brookedalton commented
https://github.com/liferay-publications/liferay-portal/assets/46908843/2dc57398-e490-4802-887d-b1da9305aaf3

2024-02-23 18:58 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/97039be0c54337fe719879d08bd5f83cb0108456">97039be0c54337fe719879d08bd5f83cb0108456</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/brookedalton/liferay-portal/tree/LPD-18648">LPD-18648</a><br/>Branch GIT ID: <a href="https://github.com/brookedalton/liferay-portal/commit/e9048c86d947b3f67bcfae740e2434187a3ad1be">e9048c86d947b3f67bcfae740e2434187a3ad1be</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-33.liferay.com/job/test-portal-source-format/2623/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-source-format/builds/2623/jenkins-report.html">here</a>.</h5></details></html>

2024-02-23 19:00 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-33.liferay.com/job/test-portal-source-format/2623/">test-portal-source-format#2623</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-source-format/builds/2623/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-publications/liferay-portal/pull/1056">liferay-publications#1056</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2542777347">[master] ci:test:sf - brookedalton &gt; liferay-publications - PR#1056 - 2024-02-23[10:54:20]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2542777347<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-33.liferay.com/job/publish-testray-report/11389/">publish-testray-report#11389</a><br/></div></div>

2024-02-26 22:45 UTC, pei-jung commented
@brookedalton can you add a test for this? You'll need to rebase on top of https://github.com/liferay-publications/liferay-portal/pull/1062 in order to add a new case since I refactored the test class quite a bit.

2024-02-27 22:31 UTC, brookedalton commented
ci:test:sf

2024-02-27 22:38 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-36.liferay.com/job/test-portal-source-format/2743/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/2743/jenkins-report.html">here</a>.</b></p>

2024-02-27 23:06 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 35 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/42dc367ad0aeb381d43580778f5d50398b4d1cfd">42dc367ad0aeb381d43580778f5d50398b4d1cfd</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/brookedalton/liferay-portal/tree/LPD-18648">LPD-18648</a><br/>Branch GIT ID: <a href="https://github.com/brookedalton/liferay-portal/commit/e527daae5c41d84dd77111e206751349f672a398">e527daae5c41d84dd77111e206751349f672a398</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-36.liferay.com/job/test-portal-source-format/2743/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/2743/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: Truncated message :
     [java] ./test.properties expected:&lt;...   #
     [java]     # Commerce [with Remote Elasticsearch 7
     [java]     #
     [java] 
     [java]     search.engine[commerce-es7-remote]=remote-elasticsearch
     [java]     test.batch.class.names.includes[commerce-es7-remote]=\$\{test.batch.class.names.includes[commerce]\}
     [java]     test.batch.dist.app.servers[commerce-es7-remote]=tomcat
     [java] 
     [java]     test.batch.names[commerce-es7-remote]=\
     [java]         functional-tomcat90-mysql57-jdk8,\
     [java]         modules-integration-mysql57-jdk8
     [java] 
     [java]     test.batch.run.property.query[functional-tomcat*-mysql*-jdk8][commerce-es7-remote]=\
     [java]         \$\{test.batch.run.property.query[functional-tomcat*-mysql*-jdk8][commerce-functional]\}
     [java] 
     [java]     #
     [java]     # Commerce with Remote Elasticsearch 8
     [java]     #
     [java] 
     [java]     search.engine[commerce-es8-remote]=remote-elasticsearch
     [java]     suite.elastic.version[commerce-es8-remote]=8.12.0
     [java]     test.batch.class.names.includes[commerce-es8-remote]=\$\{test.batch.class.names.includes[commerce]\}
     [java]     test.batch.dist.app.servers[commerce-es8-remote]=tomcat
     [java] 
     [java]     test.batch.names[commerce-es8-remote]=\
     [java]         functional-tomcat90-mysql57-jdk8,\
     [java]         modules-integration-mysql57-jdk8
     [java] 
     [java]     test.batch.run.property.query[functional-tomcat*-mysql*-jdk8][commerce-es8-remote]=\
     [java]         \$\{test.batch.run.property.query[functional-tomcat*-mysql*-jdk8][commerce-functional]\}
     [java] 
     [java]     #
     [java]     # Commerce with Remote OpenSearch 2
     [java]     #
     [java] 
     [java]     search.engine[commerce-opensearch2]=opensearch2
     [java]     test.batch.class.names.includes[commerce-opensearch2]=\$\{test.batch.class.names.includes[commerce]\}
     [java]     test.batch.dist.app.servers[commerce-opensearch2]=tomcat
     [java] 
     [java]     test.batch.names[commerce-opensearch2]=\
     [java]         functional-tomcat90-mysql57-jdk8,\
     [java]         modules-integration-mysql57-jdk8
     [java] 
     [java]     test.batch.run.property.query[functional-tomcat*-mysql*-jdk8][commerce-opensearch2]=\
     [java]         \$\{test.batch.run.property.query[functional-tomcat*-mysql*-jdk8][commerce-functional]\}</pre></details></html>

2024-02-27 23:10 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-36.liferay.com/job/test-portal-source-format/2743/">test-portal-source-format#2743</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/2743/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-publications/liferay-portal/pull/1056">liferay-publications#1056</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2544255357">[master] ci:test:sf - brookedalton &gt; liferay-publications - PR#1056 - 2024-02-27[14:32:16]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2544255357<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-36.liferay.com/job/publish-testray-report/11441/">publish-testray-report#11441</a><br/></div></div>

2024-02-27 23:11 UTC, brookedalton commented
ci:test:sf

2024-02-27 23:13 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-1.liferay.com/job/test-portal-source-format/3694/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-1.liferay.com/userContent/jobs/test-portal-source-format/builds/3694/jenkins-report.html">here</a>.</b></p>

2024-02-27 23:16 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/82525969f2bb40817ee4f68a9a68a63d47584e4f">82525969f2bb40817ee4f68a9a68a63d47584e4f</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/brookedalton/liferay-portal/tree/LPD-18648">LPD-18648</a><br/>Branch GIT ID: <a href="https://github.com/brookedalton/liferay-portal/commit/e527daae5c41d84dd77111e206751349f672a398">e527daae5c41d84dd77111e206751349f672a398</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-1.liferay.com/job/test-portal-source-format/3694/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-1.liferay.com/userContent/jobs/test-portal-source-format/builds/3694/jenkins-report.html">here</a>.</h5></details></html>

2024-02-27 23:20 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-1.liferay.com/job/test-portal-source-format/3694/">test-portal-source-format#3694</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-1.liferay.com/userContent/jobs/test-portal-source-format/builds/3694/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-publications/liferay-portal/pull/1056">liferay-publications#1056</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2544255728">[master] ci:test:sf - brookedalton &gt; liferay-publications - PR#1056 - 2024-02-27[15:11:54]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2544255728<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-1.liferay.com/job/publish-testray-report/24649/">publish-testray-report#24649</a><br/></div></div>

2024-02-28 03:54 UTC, pei-jung requested changes

2024-02-28 03:54 UTC, pei-jung commented on modules/apps/change-tracking/change-tracking-test/src/testIntegration/java/com/liferay/change/tracking/internal/test/PublicationUserNotificationHandlerTest.java
> +	public void testDeletedBodyNoLongerApplies() throws Exception {
Rename this to `testGetBodyForDeletedPublication`.

2024-02-28 17:16 UTC, brookedalton commented
ci:test:sf

2024-02-28 17:19 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-31.liferay.com/job/test-portal-source-format/6233/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/6233/jenkins-report.html">here</a>.</b></p>

2024-02-28 17:20 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/55cfba7312ff703268a0db3ef94b7f9a19aa7d67">55cfba7312ff703268a0db3ef94b7f9a19aa7d67</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/brookedalton/liferay-portal/tree/LPD-18648">LPD-18648</a><br/>Branch GIT ID: <a href="https://github.com/brookedalton/liferay-portal/commit/f5cbaccba9628bc53b2c3dfeb89644c604f3dd8d">f5cbaccba9628bc53b2c3dfeb89644c604f3dd8d</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-31.liferay.com/job/test-portal-source-format/6233/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/6233/jenkins-report.html">here</a>.</h5></details></html>

2024-02-28 17:23 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-31.liferay.com/job/test-portal-source-format/6233/">test-portal-source-format#6233</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/6233/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-publications/liferay-portal/pull/1056">liferay-publications#1056</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2544597217">[master] ci:test:sf - brookedalton &gt; liferay-publications - PR#1056 - 2024-02-28[09:17:05]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2544597217<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-31.liferay.com/job/publish-testray-report/24149/">publish-testray-report#24149</a><br/></div></div>

2024-02-28 17:54 UTC, pei-jung approved these changes

2024-02-28 17:54 UTC, pei-jung commented
ci:test:relevant

2024-02-28 17:54 UTC, pei-jung commented
ci:test:publications

2024-02-28 17:55 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest(master)/5297/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5297/jenkins-report.html">here</a>.</b></p>

2024-02-28 17:55 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>publications</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest(master)/5298/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5298/jenkins-report.html">here</a>.</b></p>

2024-02-28 19:56 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest(master)/5297/">test-portal-acceptance-pullrequest(master)#5297</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5297/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-publications/liferay-portal/pull/1056">liferay-publications#1056</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2544712952">[master] ci:test:relevant - brookedalton &gt; liferay-publications - PR#1056 - 2024-02-28[09:54:38]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2544712952<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-36.liferay.com/job/publish-testray-report/11466/">publish-testray-report#11466</a><br/></div></div>

2024-02-28 20:05 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest(master)/5298/">test-portal-acceptance-pullrequest(master)#5298</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5298/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>publications<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-publications/liferay-portal/pull/1056">liferay-publications#1056</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2544713595">[master] ci:test:publications - brookedalton &gt; liferay-publications - PR#1056 - 2024-02-28[09:54:45]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2544713595<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-36.liferay.com/job/publish-testray-report/11467/">publish-testray-report#11467</a><br/></div></div>

2024-02-28 20:14 UTC, pei-jung commented
ci:forward

2024-02-28 20:14 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2024-02-28 20:14 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
- `ci:test:relevant`
- `ci:test:sf`
- `ci:test:stable`

2024-02-28 20:15 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-30.liferay.com/job/forward-pullrequest/967//consoleFull)

2024-02-28 20:15 UTC, closed without merging

2024-02-28 20:16 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to  https://github.com/brianchandotcom/liferay-portal/pull/147676
[Console](https://test-1-30.liferay.com/job/forward-pullrequest/967//consoleFull)