LPS-196957 | Enable change tracking for country and region
liferay-publications/liferay-portal pull request #716
Opened 2023-09-28 00:24 UTC by brookedalton

https://liferay.atlassian.net/browse/LPS-196957

2023-09-28 00:24 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2023-09-28 00:27 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-source-format/3030/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/3030/jenkins-report.html">here</a>.</b></p>

2023-09-28 00:29 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/ec5ec5bca6a500f4cb4a29677f37a7b060c8e8a7">ec5ec5bca6a500f4cb4a29677f37a7b060c8e8a7</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/brookedalton/liferay-portal/tree/LPS-196957">LPS-196957</a><br/>Branch GIT ID: <a href="https://github.com/brookedalton/liferay-portal/commit/457a97a9e0268309787837e387b3e8115e6d5b21">457a97a9e0268309787837e387b3e8115e6d5b21</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-40.liferay.com/job/test-portal-source-format/3030/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/3030/jenkins-report.html">here</a>.</h5></details></html>

2023-09-28 00:31 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-source-format/3030/">test-portal-source-format#3030</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/3030/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-publications/liferay-portal/pull/716">liferay-publications#716</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2432773531">[master] ci:test:sf - brookedalton &gt; liferay-publications - PR#716 - 2023-09-27[17:24:42]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/11753/">publish-testray-report#11753</a><br/></div></div>

2023-09-28 01:58 UTC, david-truong commented
@brookedalton since you modified service builder you should run ant build-services from portal-impl to regenerate the entire project and see if any other projects can take advantage of your change

2023-09-28 20:20 UTC, pei-jung requested changes

2023-09-28 20:20 UTC, pei-jung commented on modules/apps/address/address-impl/src/main/java/com/liferay/address/internal/change/tracking/spi/reference/CountryLocalizationTableReferenceDefinition.java
> +			CompanyTable.INSTANCE.companyId);
We should define Country as the parent since the localized titles belong to a country.

2023-09-28 20:20 UTC, pei-jung commented on modules/apps/address/address-impl/src/main/java/com/liferay/address/internal/change/tracking/spi/reference/RegionLocalizationTableReferenceDefinition.java
> +			CountryLocalizationTable.INSTANCE.companyId);
We should define Region as the parent here.

2023-09-29 19:57 UTC, brookedalton commented
ci:test:sf

2023-09-29 19:59 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-source-format/3067/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/3067/jenkins-report.html">here</a>.</b></p>

2023-09-29 20:00 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/aa6a9baba1e38b5b6f7d9f7b048e64fd0a5aee21">aa6a9baba1e38b5b6f7d9f7b048e64fd0a5aee21</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/brookedalton/liferay-portal/tree/LPS-196957">LPS-196957</a><br/>Branch GIT ID: <a href="https://github.com/brookedalton/liferay-portal/commit/a3e9c54aca864c3ca0bd4cf99b5abbf8cadf5fa1">a3e9c54aca864c3ca0bd4cf99b5abbf8cadf5fa1</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-40.liferay.com/job/test-portal-source-format/3067/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/3067/jenkins-report.html">here</a>.</h5></details></html>

2023-09-29 20:03 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-source-format/3067/">test-portal-source-format#3067</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/3067/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-publications/liferay-portal/pull/716">liferay-publications#716</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2434026712">[master] ci:test:sf - brookedalton &gt; liferay-publications - PR#716 - 2023-09-29[12:57:34]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/11878/">publish-testray-report#11878</a><br/></div></div>

2023-10-02 20:12 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-source-format/3090/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/3090/jenkins-report.html">here</a>.</b></p>

2023-10-02 20:14 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/00334ca6f9fb4d92f5e98c225b104f095ee8b21e">00334ca6f9fb4d92f5e98c225b104f095ee8b21e</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/brookedalton/liferay-portal/tree/LPS-196957">LPS-196957</a><br/>Branch GIT ID: <a href="https://github.com/brookedalton/liferay-portal/commit/59b28f232511013b8214fe0beee3ec624367400d">59b28f232511013b8214fe0beee3ec624367400d</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-40.liferay.com/job/test-portal-source-format/3090/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/3090/jenkins-report.html">here</a>.</h5></details></html>

2023-10-02 20:17 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-source-format/3090/">test-portal-source-format#3090</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/3090/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-publications/liferay-portal/pull/716">liferay-publications#716</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2434779658">[master] ci:test:sf - brookedalton &gt; liferay-publications - PR#716 - 2023-10-02[13:09:32]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/11961/">publish-testray-report#11961</a><br/></div></div>

2023-10-04 18:42 UTC, pei-jung requested changes

2023-10-04 18:42 UTC, pei-jung commented on modules/apps/address/address-impl/src/main/java/com/liferay/address/internal/change/tracking/spi/reference/CountryLocalizationTableReferenceDefinition.java
> +			CountryTable.INSTANCE.companyId);
We need to define the reference by `countryId`

2023-10-04 18:42 UTC, pei-jung commented on modules/apps/address/address-impl/src/main/java/com/liferay/address/internal/change/tracking/spi/reference/RegionLocalizationTableReferenceDefinition.java
> +			RegionTable.INSTANCE.companyId);
Define the reference by `regionId`.

2023-10-04 19:55 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-source-format/1822/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/1822/jenkins-report.html">here</a>.</b></p>

2023-10-04 19:57 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f896c21dffb4913f9a7ac72f32bb565c89ae4f24">f896c21dffb4913f9a7ac72f32bb565c89ae4f24</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/brookedalton/liferay-portal/tree/LPS-196957">LPS-196957</a><br/>Branch GIT ID: <a href="https://github.com/brookedalton/liferay-portal/commit/0d08853d37a9f84a0e092027a1934949c7253f47">0d08853d37a9f84a0e092027a1934949c7253f47</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-source-format/1822/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/1822/jenkins-report.html">here</a>.</h5></details></html>

2023-10-04 20:25 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-source-format/1822/">test-portal-source-format#1822</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/1822/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-publications/liferay-portal/pull/716">liferay-publications#716</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2436484047">[master] ci:test:sf - brookedalton &gt; liferay-publications - PR#716 - 2023-10-04[12:54:14]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/7214/">publish-testray-report#7214</a><br/></div></div>

2023-10-04 22:18 UTC, pei-jung approved these changes

2023-10-04 22:18 UTC, pei-jung commented
ci:test:relevant

2023-10-04 22:18 UTC, pei-jung commented
ci:test:publications

2023-10-04 22:19 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>publications</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/6506/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6506/jenkins-report.html">here</a>.</b></p>

2023-10-04 22:19 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/3652/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3652/jenkins-report.html">here</a>.</b></p>

2023-10-05 00:06 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:publications - 90 out of 96 jobs passed in 1 hour 47 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f896c21dffb4913f9a7ac72f32bb565c89ae4f24">f896c21dffb4913f9a7ac72f32bb565c89ae4f24</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f896c21dffb4913f9a7ac72f32bb565c89ae4f24">f896c21dffb4913f9a7ac72f32bb565c89ae4f24</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2436651227">EE Development Acceptance (master) - 59 - 2023-10-04[12:41:00]</a></p><details><summary><strong>ci:test:publications - 90 out of 96 jobs PASSED</strong></summary><div><h4>6 Failed Jobs:</h4><ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/6506/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/291285/">central-requirements-jdk8/0/0</a></li></ul></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/674827/">functional-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/630181/">functional-tomcat90-mysql57-jdk8/1/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/751718/">functional-tomcat90-mysql57-jdk8/1/1</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/773379/">functional-tomcat90-mysql57-jdk8/1/2</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/797075/">functional-tomcat90-mysql57-jdk8/1/3</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/877112/">functional-tomcat90-mysql57-jdk8/1/4</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/854751/">functional-tomcat90-mysql57-jdk8/1/5</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/609200/">functional-tomcat90-mysql57-jdk8/1/6</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/376383/"><strike>functional-tomcat90-mysql57-jdk8/1/7</strike></a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/764153/">functional-tomcat90-mysql57-jdk8/1/8</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/854752/">functional-tomcat90-mysql57-jdk8/1/9</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/764154/">functional-tomcat90-mysql57-jdk8/1/10</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/877114/">functional-tomcat90-mysql57-jdk8/1/11</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/361606/">functional-tomcat90-mysql57-jdk8/1/12</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/376380/"><strike>functional-tomcat90-mysql57-jdk8/1/13</strike></a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/797077/">functional-tomcat90-mysql57-jdk8/1/14</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/751721/">functional-tomcat90-mysql57-jdk8/1/15</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/630184/">functional-tomcat90-mysql57-jdk8/1/16</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/854747/">functional-tomcat90-mysql57-jdk8/1/17</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/877108/">functional-tomcat90-mysql57-jdk8/1/18</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/854748/">functional-tomcat90-mysql57-jdk8/1/19</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/854749/">functional-tomcat90-mysql57-jdk8/1/20</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/877111/">functional-tomcat90-mysql57-jdk8/1/21</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/751717/">functional-tomcat90-mysql57-jdk8/1/22</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/854750/">functional-tomcat90-mysql57-jdk8/1/23</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/764152/">functional-tomcat90-mysql57-jdk8/1/24</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/314608/">functional-tomcat90-mysql57-jdk8/2/0</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/313105/">functional-tomcat90-mysql57-jdk8/2/1</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/247971/">functional-tomcat90-mysql57-jdk8/2/2</a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/300230/">functional-tomcat90-mysql57-jdk8/2/3</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/283150/">functional-tomcat90-mysql57-jdk8/2/4</a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/279778/">functional-tomcat90-mysql57-jdk8/2/5</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/773383/">functional-tomcat90-mysql57-jdk8/2/6</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/609203/">functional-tomcat90-mysql57-jdk8/2/7</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/709969/">functional-tomcat90-mysql57-jdk8/2/8</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/877109/">functional-tomcat90-mysql57-jdk8/2/9</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/630185/">functional-tomcat90-mysql57-jdk8/2/10</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/877116/">functional-tomcat90-mysql57-jdk8/2/11</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/674824/">functional-tomcat90-mysql57-jdk8/2/12</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/313103/">functional-tomcat90-mysql57-jdk8/2/13</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/247970/">functional-tomcat90-mysql57-jdk8/2/14</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/665474/">functional-tomcat90-mysql57-jdk8/2/15</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/720217/">functional-tomcat90-m [...]

2023-10-05 00:11 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/6506/">test-portal-acceptance-pullrequest(master)#6506</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6506/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>publications<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-publications/liferay-portal/pull/716">liferay-publications#716</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2436671730">[master] ci:test:publications - brookedalton &gt; liferay-publications - PR#716 - 2023-10-04[15:18:58]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/12085/">publish-testray-report#12085</a><br/></div></div>

2023-10-05 01:50 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:stable - 28 out of 30 jobs passed</h3><h3>:x: ci:test:relevant - 154 out of 208 jobs passed in 3 hours 17 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f896c21dffb4913f9a7ac72f32bb565c89ae4f24">f896c21dffb4913f9a7ac72f32bb565c89ae4f24</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f896c21dffb4913f9a7ac72f32bb565c89ae4f24">f896c21dffb4913f9a7ac72f32bb565c89ae4f24</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2436651227">EE Development Acceptance (master) - 59 - 2023-10-04[12:41:00]</a></p><details><summary><strong>ci:test:stable - 28 out of 30 jobs PASSED</strong></summary><div><h4>2 Failed Jobs:</h4><ul><li>build-iw-jdk8<ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/630242/">build-iw-jdk8/0/0</a></li></ul></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/697365/">central-requirements-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/291310/">functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/764204/"><strike>functional-upgrade-tomcat90-mysql57-jdk8_stable/0/0</strike></a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/797133/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/1</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/674867/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/2</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/697369/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/3</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/609257/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/4</a></li></ul></li><li>js-unit-jdk8<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/877174/">js-unit-jdk8/0/0</a></li></ul></li><li>modules-compile-jdk8<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/751779/">modules-compile-jdk8/0/0</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/630254/">modules-compile-jdk8/0/1</a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/291308/">modules-compile-jdk8/0/2</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/247999/">modules-compile-jdk8/0/3</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/283177/">modules-compile-jdk8/0/4</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/248000/">modules-compile-jdk8/0/5</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/314619/"><strike>modules-compile-jdk8/0/6</strike></a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/300247/">modules-compile-jdk8/0/7</a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/300246/">modules-compile-jdk8/0/8</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/313134/">modules-compile-jdk8/0/9</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/630245/">modules-compile-jdk8/0/10</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/376441/">modules-compile-jdk8/0/11</a></li></ul></li><li>modules-integration-mysql57-jdk8_stable<ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/630249/">modules-integration-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/697362/">modules-integration-mysql57-jdk8_stable/0/1</a></li></ul></li><li>modules-unit-jdk8_stable<ul><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/313129/">modules-unit-jdk8_stable/0/0</a></li></ul></li><li>pmd-jdk8<ul><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/283174/">pmd-jdk8/0/0</a></li></ul></li><li>portal-license-smoke-mysql57-jdk8<ul><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/697364/">portal-license-smoke-mysql57-jdk8/0/0</a></li></ul></li><li>rest-builder-jdk8<ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/764200/">rest-builder-jdk8/0/0</a></li></ul></li><li>service-builder-jdk8<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/877172/">service-builder-jdk8/0/0</a></li></ul></li><li>unit-jdk8_stable<ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/361672/">unit-jdk8_stable/0/0</a></li></ul></li><li>workspaces-compile-jdk8<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/751767/">workspaces-compile-jdk8/0/0</a></li></ul></li></ul></div><details><summary><strong>28 Successful Jobs:</strong></summary><ul/></details></details><details><summary><strong>ci:test:relevant - 154 out of 208 jobs PASSED</strong></summary><div><h4>54 Failed Jobs:</h4><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/3652/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>build-iw-jdk8<ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/630242/">build-iw-jdk8/0/0</a></li></ul></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/697365/">central-requirements-jdk8/0/0</a></li></ul></li><li>empty-osgi-core-dir-mysql57-jdk8<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/854818/">empty-osgi-core-dir-mysql57-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-db2115-jdk8<ul><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/247994/">functional-smoke-tomcat90-db2115-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-hypersonic20-jdk8<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/877169/">functional-smoke-tomcat90-hypersonic20-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk11_open<ul><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/720260/">functional-smoke-tomcat90-mysql57-jdk11_open/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/291310/">functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>functional-smoke-tomcat90-oracle193-jdk8<ul><li><a href="https://test-1-34.liferay. [...]

2023-10-05 02:01 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/3652/">test-portal-acceptance-pullrequest(master)#3652</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3652/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-publications/liferay-portal/pull/716">liferay-publications#716</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2436689729">[master] ci:test:relevant - brookedalton &gt; liferay-publications - PR#716 - 2023-10-04[15:18:53]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/7240/">publish-testray-report#7240</a><br/></div></div>

2023-10-13 15:57 UTC, pei-jung commented
Hi @brookedalton can you rebase and resolve the conflicts? Thank you!

2023-10-13 16:47 UTC, brookedalton commented
ci:test:sf

2023-10-13 16:49 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-source-format/3229/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/3229/jenkins-report.html">here</a>.</b></p>

2023-10-13 16:51 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/4822744faf073f24e00e9069d11c51a208e43635">4822744faf073f24e00e9069d11c51a208e43635</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/brookedalton/liferay-portal/tree/LPS-196957">LPS-196957</a><br/>Branch GIT ID: <a href="https://github.com/brookedalton/liferay-portal/commit/391ffc9ef7ff3c448cc1463cae347868dbc3dd68">391ffc9ef7ff3c448cc1463cae347868dbc3dd68</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-40.liferay.com/job/test-portal-source-format/3229/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/3229/jenkins-report.html">here</a>.</h5></details></html>

2023-10-13 18:04 UTC, pei-jung commented
ci:forward

2023-10-13 18:04 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2023-10-13 18:04 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
- `ci:test:sf`

2023-10-13 18:05 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/3774/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3774/jenkins-report.html">here</a>.</b></p>

2023-10-13 18:48 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-source-format/3229/">test-portal-source-format#3229</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/3229/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-publications/liferay-portal/pull/716">liferay-publications#716</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2441135412">[master] ci:test:sf - brookedalton &gt; liferay-publications - PR#716 - 2023-10-13[09:48:02]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/12490/">publish-testray-report#12490</a><br/></div></div>

2023-10-13 21:01 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:stable - 29 out of 30 jobs passed</h3><h3>:x: ci:test:relevant - 156 out of 208 jobs passed in 2 hours 54 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/4822744faf073f24e00e9069d11c51a208e43635">4822744faf073f24e00e9069d11c51a208e43635</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/4822744faf073f24e00e9069d11c51a208e43635">4822744faf073f24e00e9069d11c51a208e43635</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2440862405">EE Development Acceptance (master) - 76 - 2023-10-12[20:40:59]</a></p><details><summary><strong>ci:test:stable - 29 out of 30 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li>build-iw-jdk8<ul><li><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/285272/">build-iw-jdk8/0/0</a></li></ul></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/622311/">central-requirements-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/281233/">functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/290707/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/298727/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/1</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/320927/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/2</a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/277361/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/3</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/392049/"><strike>functional-upgrade-tomcat90-mysql57-jdk8_stable/0/4</strike></a></li></ul></li><li>js-unit-jdk8<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/869536/">js-unit-jdk8/0/0</a></li></ul></li><li>modules-compile-jdk8<ul><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/277574/">modules-compile-jdk8/0/0</a></li><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/302768/">modules-compile-jdk8/0/1</a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/277364/">modules-compile-jdk8/0/2</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/622327/">modules-compile-jdk8/0/3</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/290709/">modules-compile-jdk8/0/4</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/279363/">modules-compile-jdk8/0/5</a></li><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/302769/">modules-compile-jdk8/0/6</a></li><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/302770/">modules-compile-jdk8/0/7</a></li><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/281231/">modules-compile-jdk8/0/8</a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/306908/">modules-compile-jdk8/0/9</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/320922/">modules-compile-jdk8/0/10</a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/306897/">modules-compile-jdk8/0/11</a></li></ul></li><li>modules-integration-mysql57-jdk8_stable<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/869521/">modules-integration-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/375395/">modules-integration-mysql57-jdk8_stable/0/1</a></li></ul></li><li>modules-unit-jdk8_stable<ul><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/281028/">modules-unit-jdk8_stable/0/0</a></li></ul></li><li>pmd-jdk8<ul><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/320929/">pmd-jdk8/0/0</a></li></ul></li><li>portal-license-smoke-mysql57-jdk8<ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/645833/">portal-license-smoke-mysql57-jdk8/0/0</a></li></ul></li><li>rest-builder-jdk8<ul><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/281022/">rest-builder-jdk8/0/0</a></li></ul></li><li>service-builder-jdk8<ul><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/282994/">service-builder-jdk8/0/0</a></li></ul></li><li>unit-jdk8_stable<ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/622309/">unit-jdk8_stable/0/0</a></li></ul></li><li>workspaces-compile-jdk8<ul><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/271527/">workspaces-compile-jdk8/0/0</a></li></ul></li></ul></div><details><summary><strong>29 Successful Jobs:</strong></summary><ul/></details></details><details><summary><strong>ci:test:relevant - 156 out of 208 jobs PASSED</strong></summary><div><h4>52 Failed Jobs:</h4><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/3774/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>build-iw-jdk8<ul><li><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/285272/">build-iw-jdk8/0/0</a></li></ul></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/622311/">central-requirements-jdk8/0/0</a></li></ul></li><li>empty-osgi-core-dir-mysql57-jdk8<ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/375397/">empty-osgi-core-dir-mysql57-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-db2115-jdk8<ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/776780/">functional-smoke-tomcat90-db2115-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-hypersonic20-jdk8<ul><li><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/285273/">functional-smoke-tomcat90-hypersonic20-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk11_open<ul><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/245999/">functional-smoke-tomcat90-mysql57-jdk11_open/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/281233/">functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>functional-smoke-tomcat90-oracle193-jdk8<ul><li><a href="https://test-1-10.liferay.com/job/test-p [...]

2023-10-13 21:16 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/3774/">test-portal-acceptance-pullrequest(master)#3774</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3774/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-publications/liferay-portal/pull/716">liferay-publications#716</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2441187534">[master] ci:test:relevant - brookedalton &gt; liferay-publications - PR#716 - 2023-10-13[11:04:46]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/7530/">publish-testray-report#7530</a><br/></div></div>

2023-10-16 19:15 UTC, brookedalton commented
ci:test:sf

2023-10-16 19:19 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-18.liferay.com/job/test-portal-source-format/7198/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-18.liferay.com/userContent/jobs/test-portal-source-format/builds/7198/jenkins-report.html">here</a>.</b></p>

2023-10-16 19:22 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 7 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/315e3683f545ef84650d9d001986d907ed4fffdd">315e3683f545ef84650d9d001986d907ed4fffdd</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/brookedalton/liferay-portal/tree/LPS-196957">LPS-196957</a><br/>Branch GIT ID: <a href="https://github.com/brookedalton/liferay-portal/commit/be6a6e3035208596ed27d9a87c79837c8cf6d126">be6a6e3035208596ed27d9a87c79837c8cf6d126</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-18.liferay.com/job/test-portal-source-format/7198/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-18.liferay.com/userContent/jobs/test-portal-source-format/builds/7198/jenkins-report.html">here</a>.</h5></details></html>

2023-10-16 19:27 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-18.liferay.com/job/test-portal-source-format/7198/">test-portal-source-format#7198</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-18.liferay.com/userContent/jobs/test-portal-source-format/builds/7198/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-publications/liferay-portal/pull/716">liferay-publications#716</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2441982060">[master] ci:test:sf - brookedalton &gt; liferay-publications - PR#716 - 2023-10-16[12:15:29]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-18.liferay.com/job/publish-testray-report/4449/">publish-testray-report#4449</a><br/></div></div>

2023-10-16 22:18 UTC, brookedalton commented
ci:test:sf

2023-10-16 22:22 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-38.liferay.com/job/test-portal-source-format/5131/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/5131/jenkins-report.html">here</a>.</b></p>

2023-10-16 22:24 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/8cbe8c8834c6d80de942ac104221a67c6069c4cb">8cbe8c8834c6d80de942ac104221a67c6069c4cb</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/brookedalton/liferay-portal/tree/LPS-196957">LPS-196957</a><br/>Branch GIT ID: <a href="https://github.com/brookedalton/liferay-portal/commit/e074d23312681e61530da6898270459a6d908778">e074d23312681e61530da6898270459a6d908778</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-38.liferay.com/job/test-portal-source-format/5131/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/5131/jenkins-report.html">here</a>.</h5></details></html>

2023-10-16 22:25 UTC, brookedalton commented
ci:test:relevant

2023-10-16 22:29 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-38.liferay.com/job/test-portal-source-format/5131/">test-portal-source-format#5131</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/5131/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-publications/liferay-portal/pull/716">liferay-publications#716</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2442054055">[master] ci:test:sf - brookedalton &gt; liferay-publications - PR#716 - 2023-10-16[15:20:29]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-38.liferay.com/job/publish-testray-report/19028/">publish-testray-report#19028</a><br/></div></div>

2023-10-16 22:42 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest(master)/8408/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8408/jenkins-report.html">here</a>.</b></p>

2023-10-17 01:32 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 30 out of 30 jobs passed</h3><h3>:x: ci:test:relevant - 156 out of 209 jobs passed in 2 hours 49 minutes</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/80">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:1297401_8408</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/8cbe8c8834c6d80de942ac104221a67c6069c4cb">8cbe8c8834c6d80de942ac104221a67c6069c4cb</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/fc5a961217432041415d13a17ef03bb09e4fb3a3">fc5a961217432041415d13a17ef03bb09e4fb3a3</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2441985577">EE Development Acceptance (master) - 79 - 2023-10-16[08:42:51]</a></p><details><summary><strong>ci:test:stable - 30 out of 30 jobs PASSED</strong></summary><details><summary><strong>30 Successful Jobs:</strong></summary><ul/></details></details><details><summary><strong>ci:test:relevant - 156 out of 209 jobs PASSED</strong></summary><div><h4>53 Failed Jobs:</h4><ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest(master)/8408/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>build-iw-jdk8<ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/649312/">build-iw-jdk8/0/0</a></li></ul></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/873086/">central-requirements-jdk8/0/0</a></li></ul></li><li>empty-osgi-core-dir-mysql57-jdk8<ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/378924/">empty-osgi-core-dir-mysql57-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-db2115-jdk8<ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/779955/">functional-smoke-tomcat90-db2115-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-hypersonic20-jdk8<ul><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/735742/">functional-smoke-tomcat90-hypersonic20-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk11_open<ul><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/735741/">functional-smoke-tomcat90-mysql57-jdk11_open/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/304261/">functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>functional-smoke-tomcat90-oracle193-jdk8<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/747111/">functional-smoke-tomcat90-oracle193-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-postgresql144-jdk8<ul><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/680852/">functional-smoke-tomcat90-postgresql144-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-postgresql153-jdk8<ul><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/286920/">functional-smoke-tomcat90-postgresql153-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-sqlserver2019-jdk8<ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/378919/">functional-smoke-tomcat90-sqlserver2019-jdk8/0/0</a></li></ul></li><li>functional-smoke-wildfly180-mariadb104-jdk8<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/895428/">functional-smoke-wildfly180-mariadb104-jdk8/0/0</a></li></ul></li><li>functional-smoke-wildfly180-mariadb106-jdk8<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/789765/">functional-smoke-wildfly180-mariadb106-jdk8/0/0</a></li></ul></li><li>functional-tomcat90-mysql57-chrome100-jdk8<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/789768/">functional-tomcat90-mysql57-chrome100-jdk8/0/0</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/813710/">functional-tomcat90-mysql57-chrome100-jdk8/0/1</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/378923/">functional-tomcat90-mysql57-chrome100-jdk8/0/2</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/873083/">functional-tomcat90-mysql57-chrome100-jdk8/0/3</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/649317/">functional-tomcat90-mysql57-chrome100-jdk8/0/4</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/712271/">functional-tomcat90-mysql57-chrome100-jdk8/0/5</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/625203/">functional-tomcat90-mysql57-chrome100-jdk8/0/6</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/779949/">functional-tomcat90-mysql57-chrome100-jdk8/0/7</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/688349/">functional-tomcat90-mysql57-chrome100-jdk8/0/8</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/395266/">functional-tomcat90-mysql57-chrome100-jdk8/0/9</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/292254/">functional-tomcat90-mysql57-chrome100-jdk8/0/10</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/256910/">functional-tomcat90-mysql57-chrome100-jdk8/0/11</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/290138/">functional-tomcat90-mysql57-chrome100-jdk8/0/12</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/649326/">functional-tomcat90-mysql57-chrome100-jdk8/0/13</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/688355/">functional-tomcat90-mysql57-chrome100-jdk8/0/14</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/322889/">functional-tomcat90-mysql57-chrome100-jdk8/0/15</a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/308524/">functional-tomcat90-mysql57-chrome100-jdk8/0/16</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/292255/">functional-tomcat90-mysql57-chrome100-jdk8/0/17</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/895427/">functional-tomcat90-mysql57-chrome100-jdk8/0/18</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/895426/">functional-tomcat90-mysql57-chrome100-jdk8/0/19</a></li><li><a href="https://test-1-39.liferay.com/job/test-p [...]

2023-10-17 01:45 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest(master)/8408/">test-portal-acceptance-pullrequest(master)#8408</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8408/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-publications/liferay-portal/pull/716">liferay-publications#716</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2442139172">[master] ci:test:relevant - brookedalton &gt; liferay-publications - PR#716 - 2023-10-16[15:41:50]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-29.liferay.com/job/publish-testray-report/18784/">publish-testray-report#18784</a><br/></div></div>

2023-10-17 16:05 UTC, brookedalton commented
ci:forward:force

2023-10-17 16:06 UTC, liferay-continuous-integration commented
All required test suite(s) completed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-28.liferay.com/job/forward-pullrequest/773//consoleFull)

2023-10-17 16:10 UTC, liferay-continuous-integration commented
Error has occurred while attempting to forward pull request to `brianchandotcom`. Retrying in 1 minute...
See console log for detail:[Full Console](https://test-1-28.liferay.com/job/forward-pullrequest/773//consoleFull)

2023-10-17 16:12 UTC, liferay-continuous-integration commented
Error has occurred while attempting to forward pull request to `brianchandotcom`. Retrying in 1 minute...
See console log for detail:[Full Console](https://test-1-28.liferay.com/job/forward-pullrequest/773//consoleFull)

2023-10-17 16:32 UTC, closed without merging

2023-10-17 16:32 UTC, brookedalton commented
Manually forwarded: https://github.com/brianchandotcom/liferay-portal/pull/142327