LPS-201886 Confirm before deleting
liferay-publications/liferay-portal pull request #865
Opened 2023-11-22 18:21 UTC by brookedalton

https://liferay.atlassian.net/browse/LPS-201886

2023-11-22 18:21 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2023-11-22 18:24 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-19.liferay.com/job/test-portal-source-format/7334/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-19.liferay.com/userContent/jobs/test-portal-source-format/builds/7334/jenkins-report.html">here</a>.</b></p>

2023-11-22 18:26 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/38131bd1c68de68ae139a595824a7acdf2191b2c">38131bd1c68de68ae139a595824a7acdf2191b2c</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/brookedalton/liferay-portal/tree/LPS-201886">LPS-201886</a><br/>Branch GIT ID: <a href="https://github.com/brookedalton/liferay-portal/commit/3db4a5a9848ac7cc9a12bb6acaafb48ae93c172a">3db4a5a9848ac7cc9a12bb6acaafb48ae93c172a</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-19.liferay.com/job/test-portal-source-format/7334/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-19.liferay.com/userContent/jobs/test-portal-source-format/builds/7334/jenkins-report.html">here</a>.</h5></details></html>

2023-11-22 18:30 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-19.liferay.com/job/test-portal-source-format/7334/">test-portal-source-format#7334</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-19.liferay.com/userContent/jobs/test-portal-source-format/builds/7334/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-publications/liferay-portal/pull/865">liferay-publications#865</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2463653247">[master] ci:test:sf - brookedalton &gt; liferay-publications - PR#865 - 2023-11-22[10:22:04]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-19.liferay.com/job/publish-testray-report/4037/">publish-testray-report#4037</a><br/></div></div>

2023-11-27 01:40 UTC, pei-jung requested changes

2023-11-27 01:40 UTC, pei-jung commented on modules/apps/change-tracking/change-tracking-web/src/main/java/com/liferay/change/tracking/web/internal/display/context/PublicationsDisplayContext.java
> +				"async"),
This reverts your fix in https://github.com/liferay/liferay-portal/commit/61e69aa8dac8bc4690a5cb012b54c96c222c0587 .

Please resend with a solution that takes care of both issues.

2023-11-29 17:32 UTC, pei-jung requested changes

2023-11-29 17:32 UTC, pei-jung commented on modules/apps/change-tracking/change-tracking-web/src/main/resources/META-INF/resources/publications/view_publications.jsp
> +		propsTransformer="publications/js/DeletePublicationsFDSPropsTransformer"
Move the js file to the `js/components` directory.

2023-11-29 17:32 UTC, pei-jung commented on modules/apps/change-tracking/change-tracking-web/src/main/resources/META-INF/resources/publications/js/DeletePublicationsFDSPropsTransformer.js
> +		const deleteURL = itemData.actions.delete.href;
Declare var close to its usage.

2023-11-29 17:32 UTC, pei-jung commented on modules/apps/change-tracking/change-tracking-web/src/main/resources/META-INF/resources/publications/js/DeletePublicationsFDSPropsTransformer.js
> +					window.location.reload();
Add line break

2023-11-29 17:32 UTC, pei-jung commented on modules/apps/change-tracking/change-tracking-web/src/main/resources/META-INF/resources/publications/js/DeletePublicationsFDSPropsTransformer.js
> +						throw new Error();
Use `openToast` to display the error

2023-11-29 18:01 UTC, brookedalton commented
ci:test:sf

2023-11-29 18:05 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-10.liferay.com/job/test-portal-source-format/5081/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-10.liferay.com/userContent/jobs/test-portal-source-format/builds/5081/jenkins-report.html">here</a>.</b></p>

2023-11-29 18:08 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 7 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/6849032411624640d37c4b08bbda963d6d6869fa">6849032411624640d37c4b08bbda963d6d6869fa</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/brookedalton/liferay-portal/tree/LPS-201886">LPS-201886</a><br/>Branch GIT ID: <a href="https://github.com/brookedalton/liferay-portal/commit/7b7643f5b10e93655b1737f570ab7c6622d28273">7b7643f5b10e93655b1737f570ab7c6622d28273</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-10.liferay.com/job/test-portal-source-format/5081/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-10.liferay.com/userContent/jobs/test-portal-source-format/builds/5081/jenkins-report.html">here</a>.</h5></details></html>

2023-11-29 18:16 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-10.liferay.com/job/test-portal-source-format/5081/">test-portal-source-format#5081</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-10.liferay.com/userContent/jobs/test-portal-source-format/builds/5081/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-publications/liferay-portal/pull/865">liferay-publications#865</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2467554859">[master] ci:test:sf - brookedalton &gt; liferay-publications - PR#865 - 2023-11-29[10:02:12]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-10.liferay.com/job/publish-testray-report/4997/">publish-testray-report#4997</a><br/></div></div>

2023-11-29 19:01 UTC, pei-jung approved these changes
@brookedalton good job figuring out a solution for this! 👍

2023-11-29 19:01 UTC, pei-jung commented
ci:test:publications

2023-11-29 19:01 UTC, pei-jung commented
ci:test:relevant

2023-11-29 19:55 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>publications</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest(master)/8586/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8586/jenkins-report.html">here</a>.</b></p>

2023-11-29 23:14 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 31 out of 31 jobs passed</h3><h3>:x: ci:test:relevant - 77 out of 81 jobs passed in 3 hours 19 minutes</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/208">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:1397401_8587</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/4493e70da78e4ba2255b78ca54b7f443921218ea">4493e70da78e4ba2255b78ca54b7f443921218ea</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c12b85af0da8864ec44b9b0052406ebb42372050">c12b85af0da8864ec44b9b0052406ebb42372050</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2467695289">EE Development Acceptance (master) - 207 - 2023-11-29[08:40:54]</a></p><details><summary><strong>ci:test:stable - 31 out of 31 jobs PASSED</strong></summary><details><summary><strong>31 Successful Jobs:</strong></summary><ul/></details></details><details><summary><strong>ci:test:relevant - 77 out of 81 jobs PASSED</strong></summary><div><h4>4 Failed Jobs:</h4><ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest(master)/8587/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>build-iw-jdk8<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/830056/">build-iw-jdk8/0/0</a></li></ul></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/471525/">central-requirements-jdk8/0/0</a></li></ul></li><li>empty-osgi-core-dir-mysql57-jdk8<ul><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/302850/">empty-osgi-core-dir-mysql57-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-db2115-jdk8<ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/843156/">functional-smoke-tomcat90-db2115-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-hypersonic20-jdk8<ul><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/309202/">functional-smoke-tomcat90-hypersonic20-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk11_open<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/830059/">functional-smoke-tomcat90-mysql57-jdk11_open/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/874448/">functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>functional-smoke-tomcat90-oracle193-jdk8<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/958747/">functional-smoke-tomcat90-oracle193-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-postgresql144-jdk8<ul><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/287428/">functional-smoke-tomcat90-postgresql144-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-postgresql153-jdk8<ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/450039/">functional-smoke-tomcat90-postgresql153-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-sqlserver2019-jdk8<ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/684839/">functional-smoke-tomcat90-sqlserver2019-jdk8/0/0</a></li></ul></li><li>functional-smoke-wildfly180-mariadb104-jdk8<ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/843152/">functional-smoke-wildfly180-mariadb104-jdk8/0/0</a></li></ul></li><li>functional-smoke-wildfly180-mariadb106-jdk8<ul><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/319237/">functional-smoke-wildfly180-mariadb106-jdk8/0/0</a></li></ul></li><li>functional-tomcat90-mysql57-chrome100-jdk8<ul><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/302851/">functional-tomcat90-mysql57-chrome100-jdk8/0/0</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/874450/">functional-tomcat90-mysql57-chrome100-jdk8/0/1</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/843157/">functional-tomcat90-mysql57-chrome100-jdk8/0/2</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/801316/">functional-tomcat90-mysql57-chrome100-jdk8/0/3</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/949836/">functional-tomcat90-mysql57-chrome100-jdk8/0/4</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/273405/">functional-tomcat90-mysql57-chrome100-jdk8/0/5</a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/292315/">functional-tomcat90-mysql57-chrome100-jdk8/0/6</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/757608/">functional-upgrade-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/958746/">functional-upgrade-tomcat90-mysql57-jdk8/0/1</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/874449/">functional-upgrade-tomcat90-mysql57-jdk8/0/2</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/717312/">functional-upgrade-tomcat90-mysql57-jdk8/0/3</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/801314/">functional-upgrade-tomcat90-mysql57-jdk8/0/4</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/801315/">functional-upgrade-tomcat90-mysql57-jdk8/0/5</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/843155/">functional-upgrade-tomcat90-mysql57-jdk8/0/6</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/958745/">functional-upgrade-tomcat90-mysql57-jdk8/0/7</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/717311/">functional-upgrade-tomcat90-mysql57-jdk8/0/8</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/302849/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/309201/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/1</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/801313/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/2</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/319239/ [...]

2023-11-29 23:17 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest(master)/8587/">test-portal-acceptance-pullrequest(master)#8587</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8587/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-publications/liferay-portal/pull/865">liferay-publications#865</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2467810964">[master] ci:test:relevant - brookedalton &gt; liferay-publications - PR#865 - 2023-11-29[11:55:07]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-39.liferay.com/job/publish-testray-report/17615/">publish-testray-report#17615</a><br/></div></div>

2023-11-29 23:24 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:publications - 88 out of 101 jobs passed in 3 hours 30 minutes</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/208">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:1397401_8586</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/4493e70da78e4ba2255b78ca54b7f443921218ea">4493e70da78e4ba2255b78ca54b7f443921218ea</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c12b85af0da8864ec44b9b0052406ebb42372050">c12b85af0da8864ec44b9b0052406ebb42372050</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2467695289">EE Development Acceptance (master) - 207 - 2023-11-29[08:40:54]</a></p><details><summary><strong>ci:test:publications - 88 out of 101 jobs PASSED</strong></summary><div><h4>13 Failed Jobs:</h4><ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest(master)/8586/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/273404/">central-requirements-jdk8/0/0</a></li></ul></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/843147/">functional-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/471510/">functional-tomcat90-mysql57-jdk8/1/0</a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/302844/">functional-tomcat90-mysql57-jdk8/1/1</a></li><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/305810/">functional-tomcat90-mysql57-jdk8/1/2</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/471511/">functional-tomcat90-mysql57-jdk8/1/3</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/326007/"><strike>functional-tomcat90-mysql57-jdk8/1/4</strike></a></li><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/309194/">functional-tomcat90-mysql57-jdk8/1/5</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/471513/">functional-tomcat90-mysql57-jdk8/1/6</a></li><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/309195/">functional-tomcat90-mysql57-jdk8/1/7</a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/302845/">functional-tomcat90-mysql57-jdk8/1/8</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/471512/">functional-tomcat90-mysql57-jdk8/1/9</a></li><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/305813/">functional-tomcat90-mysql57-jdk8/1/10</a></li><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/309198/"><strike>functional-tomcat90-mysql57-jdk8/1/11</strike></a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/326011/">functional-tomcat90-mysql57-jdk8/1/12</a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/302848/">functional-tomcat90-mysql57-jdk8/1/13</a></li><li><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/307660/"><strike>functional-tomcat90-mysql57-jdk8/1/14</strike></a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/949832/">functional-tomcat90-mysql57-jdk8/1/15</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/717308/">functional-tomcat90-mysql57-jdk8/1/16</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/757603/">functional-tomcat90-mysql57-jdk8/1/17</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/471519/"><strike>functional-tomcat90-mysql57-jdk8/1/18</strike></a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/949829/"><strike>functional-tomcat90-mysql57-jdk8/1/19</strike></a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/843148/">functional-tomcat90-mysql57-jdk8/1/20</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/717306/">functional-tomcat90-mysql57-jdk8/1/21</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/757604/"><strike>functional-tomcat90-mysql57-jdk8/1/22</strike></a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/793563/">functional-tomcat90-mysql57-jdk8/1/23</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/471520/">functional-tomcat90-mysql57-jdk8/1/24</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/471523/">functional-tomcat90-mysql57-jdk8/2/0</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/740043/">functional-tomcat90-mysql57-jdk8/2/1</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/874447/">functional-tomcat90-mysql57-jdk8/2/2</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/757607/"><strike>functional-tomcat90-mysql57-jdk8/2/3</strike></a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/793567/">functional-tomcat90-mysql57-jdk8/2/4</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/801310/">functional-tomcat90-mysql57-jdk8/2/5</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/780567/">functional-tomcat90-mysql57-jdk8/2/6</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/958740/">functional-tomcat90-mysql57-jdk8/2/7</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/843151/">functional-tomcat90-mysql57-jdk8/2/8</a></li><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/305807/">functional-tomcat90-mysql57-jdk8/2/9</a></li><li><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/307659/">functional-tomcat90-mysql57-jdk8/2/10</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/801306/">functional-tomcat90-mysql57-jdk8/2/11</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/717305/">functional-tomcat90-mysql57-jdk8/2/12</a></li><li><a href="https://test-1-18.liferay.com/job/test-portal-ac [...]

2023-11-29 23:29 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest(master)/8586/">test-portal-acceptance-pullrequest(master)#8586</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8586/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>publications<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-publications/liferay-portal/pull/865">liferay-publications#865</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2467814038">[master] ci:test:publications - brookedalton &gt; liferay-publications - PR#865 - 2023-11-29[11:54:42]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-39.liferay.com/job/publish-testray-report/17617/">publish-testray-report#17617</a><br/></div></div>

2023-11-30 08:32 UTC, suilin commented
Hi @brookedalton @pei-jung, I found two issues for current changes, I updated the issues as follows can you look at them?

- Invited Viewer users can delete the publication
1. Add a new user
2. Enalbe Publications
3. Add a new publication
4. Add some contents
5. Invited the user as a Viewer
6. Login with the new user
Actual result: The user not only has permission to view a publication but also has permission to delete it.
Expected Result: The user should only have permission to view the publication.


- Sandbox publication name contains the wrong time after deleting
1. Add a new user with a Publications User role
2. Enable Publications and Sandbox Only
3. Add a new publication
4. Login with the new user
5. The sandbox publication shows up
6. Delete the publication
Actual result: The new sandbox publication shows up but the name's time is a bit earlier than the current UTC time. Such as the publication name should be `usersn - 11/29/23 10:47` but  `usersn - 11/29/23 10:46`. I also found that after deleting the publication, the alert message shows up before reloading the page to show the publication is gone. Previously the alert message shows up after showing the publication is gone
Expected Result: The new sandbox publication shows up and the name time is the same as the current UTC time.

2023-12-01 01:15 UTC, pei-jung commented
Resent with fixes https://github.com/liferay-publications/liferay-portal/pull/878

2023-12-01 01:15 UTC, closed without merging